### PR TITLE
Replace join_chat boolean with chat: ChatPresence

### PR DESCRIPTION
**Pull request by Tkd-Alex**
# Description

Allowed values for `chat` are:
- `ALWAYS` Join in IRC chat and never leave
- `NEVER` Never join IRC chat
- `ONLINE` Partecipate to IRC chat if the streamer is online (leave if offline)
- `OFFLINE` Partecipate to IRC chat if the streamer is offline (leave if online)

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality not to work as expected)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (README.md)
- [x] My changes generate no new warnings
- [x] Any dependent changes have been updated in requirements.txt

### CODE REVIEW

**Comment by RakSrinaNa** [comment]
As it is this is a breaking change no ? (non-breaking is currently checked)
`join_chat=True` of previous configurations will break when this is merged.

**Comment by Tkd-Alex** [comment]
uhm yes could break all the configurations files 🤔 we could maintain a backward compatibility with the `join_chat=True` as `ChatPresence.online`

**Comment by Tkd-Alex** [comment]
Edit: **Marked as Breaking change**

**Comment by Yishaqel** [comment]
¿Does this branch currently work? I am interested in giving it a try.

**Comment by Tkd-Alex** [comment]
@Yishaqel yup

**Comment by Yishaqel** [comment]
> @Yishaqel yup

When I try to make it work I also get the error 'Error pagination' so I guess it is not up to date.

**Comment by Tkd-Alex** [comment]
> > @Yishaqel yup
> 
> When I try to make it work I also get the error 'Error pagination' so I guess it is not up to date.

Please try now :)

**Comment by Yishaqel** [comment]
> > > @Yishaqel yup
> > 
> > 
> > When I try to make it work I also get the error 'Error pagination' so I guess it is not up to date.
> 
> Please try now :)

Now it works, I will be in this branch checking that everything works as it should.

**Comment by Tkd-Alex** [comment]
> > > > @Yishaqel yup
> > > 
> > > 
> > > When I try to make it work I also get the error 'Error pagination' so I guess it is not up to date.
> > 
> > 
> > Please try now :)
> 
> Now it works, I will be in this branch checking that everything works as it should.

any news? :)

**Pull request merged**
