### PR TITLE
Switchable Analytics

### PR DESCRIPTION
**Pull request by rdavydov**
# Description

### `enable_analytics` option in `twitch_minerfile` toggles Analytics needed for the `analytics()` method

Disabling Analytics significantly reduces memory consumption and saves some disk space by not creating and writing `/analytics/*.json`.

Set this option to `True` if you need Analytics. Otherwise set this option to `False` (default value).

See `example.py`. If no such option - defaults to `False`.

Fixes # [(issue)](https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2/issues/2)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

From tests that I've done on my Windows 10 PC - it reduces memory consumption significantly - from **800 MB** with analytics enabled to **40 MB** with disabled. On my Linux boxes it also becomes less memory-hungry.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (README.md)
- [x] My changes generate no new warnings
- [x] Any dependent changes have been updated in requirements.txt

### CODE REVIEW

**Comment by ColinShark** [comment]
Wouldn't it make more sense to have this as a setting in the `run.py` instead of as an optional file you have to create?

```python
twitch_miner.mine(  # Using this as only mine() actually invokes the whole process
    [ "streamer1", "streamer2" ], # list of our streamers
    store_analytics = True  # default behaviour, False to disable
)
```
Maybe a different setting elsewhere, but you get the idea.

**Comment by rdavydov** [comment]
@ColinShark That was my first approach, but using a config parameter didn't work as expected. I haven't been able to pass it through the Settings object between modules.
I've tried adding:
```
class Settings(object):
    __slots__ = ["logger", "enable_analytics", "streamer_settings"]
```
And then checked Settings.enable_analytics, but got either <member 'enable_analytics' of 'Settings' objects> or it was always True. In fact, I've tried adding a bool variable to both logger and streamer_settings, but had no luck passing it to the corresponding modules.

So, the second approach was to pass the parameter between modules by importing a module with it. And I thought - why don't just check for the module itself. Seemed like the easiest solution.

**Comment by rdavydov** [comment]
Here's the release "for noobs" as usual: https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2/releases/tag/1.3
;)

**Comment by rdavydov** [comment]
Decided to move from `enableAnalytics` to `ENABLE_ANALYTICS` (and so on) in the file name and in the code, because it is a flag and flags should be CAPS_NAMED.

Also, as a bonus, added:

### `DELETE_PYCACHE.bat` Windows batch file to remove `__pycache__`

- Get rid of the old cache files faster, especially after new updates.

Here's the release "for noobs" as usual: https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2/releases/tag/1.3.1
;)

**Comment by rdavydov** [comment]
@ColinShark After thinking and looking through the code properly, I understood what you meant and why proposed exactly the mine() method.

I think we can pass the analytics option through it all the way up to WebSocketsPool. Will try to implement it, this will be the proper way.

**Comment by mikedoyle322** [comment]
image
I get this error when the bot places bets. I tried delete ENABLE_ANALYTICS.py or renamed it but no help
The bets were placed tho, just annoying to see it in console

**Comment by rdavydov** [comment]
@mikedoyle322 Could you specify how exactly the script was installed on your system? Because it is located in `/usr/src/app` - I guess you didn't put it there manually? What link did you download it from?

**Comment by mikedoyle322** [comment]
@rdavydov I use your release for noobs source code, I host the app on fly.io, I think they use Docker and usr/src/app/ is their root folder?? (I have to copy my cookies to /usr/src/app/cookies for the app to work).
image
maybe I should copy everything to usr/src/app/

**Comment by rdavydov** [comment]
@mikedoyle322 lines 11 and 12 on your screenshot looks pretty strange. Is your account named "21mtd"? Anyway, you could try copying as you suggested and check the result.

**Comment by mikedoyle322** [comment]
@rdavydov yeah i was testing if the analytics files were corrupted with those lines but still same error, the bet works, just some weird errors on console, maybe i should just ignore them 😄

**Comment by mikedoyle322** [comment]
a little update, i reversed back to the old version with analytics, no more error but for sure it uses more memory than this

**Comment by NoxRare** [comment]
As a Docker user myself, I would like to point out that once the docker image is built we have no way of changing this feature, either we build the image with or without analytics. It would be really cool if we could find another way of doing this as I would really like the lower memory without mulipule images.

**Comment by rdavydov** [comment]
OK, guys, I'll put an effort and see what I can do to make it configurable by a setting.
I have an idea, maybe I'll crack it.

**Comment by rdavydov** [comment]
Cracked it! Will post an update soon.

**Comment by rdavydov** [comment]
### `analytics` option in `twitch_minerfile` toggles Analytics

Disabling Analytics significantly reduces memory consumption and saves some disk space by not creating and writing `/analytics/*.json`.

Set this option to `True` if you need Analytics. Otherwise set this option to `False` (default value).

See `example.py`.

**Comment by rdavydov** [comment]
Here's the release "for noobs" as usual: https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2/releases/tag/1.3.3
😉

**Comment by NoxRare** [comment]
> ### `analytics` option in `twitch_minerfile` toggles Analytics
> Disabling Analytics significantly reduces memory consumption and saves some disk space by not creating and writing `/analytics/*.json`.
> 
> Set this option to `True` if you need Analytics. Otherwise set this option to `False` (default value).
> 
> See `example.py`.

What do I do with this part: twitch_miner.analytics(host="127.0.0.1", port=5000, refresh=5, days_ago=7)

This version now breaks the bots I have that I want analytics on, I get this: AttributeError: analytics
Yes I have changed it from False to True.

**Comment by rdavydov** [comment]
@NoxRare Thanks for the report, I didn't actually test if the Analytics frontend works correctly, LOL. :)
I'll make some changes to fix it soon.

**Comment by mikedoyle322** [comment]
> Edit: Removed that part,and changed analytics to True as seen in the example.py and still does not work, ram usage goes up but cant access the page, my guess is because the server is bound to 127.0.0.1 - This makes it only accessable locally and therefore breaks access for people who are running it on Servers (Such as me)

You should change it to 0.0.0.0 and make sure your host has the same port too
https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2#analytics

**Comment by NoxRare** [comment]
> 

Its almost like you didnt read my edits, I obviously changed it to 0.0.0.0 and my host has all ports opened.
I'm also running it thru docker so I the port on the container doesnt matter as I can change it when going out.
Smh

**Comment by NoxRare** [comment]
> > Edit: Removed that part,and changed analytics to True as seen in the example.py and still does not work, ram usage goes up but cant access the page, my guess is because the server is bound to 127.0.0.1 - This makes it only accessable locally and therefore breaks access for people who are running it on Servers (Such as me)
> 
> You should change it to 0.0.0.0 and make sure your host has the same port too https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2#analytics

Its almost like you didnt read my edits, I obviously changed it to 0.0.0.0 and my host has all ports opened.
I'm also running it thru docker so I the port on the container doesnt matter as I can change it when going out.
Smh

**Comment by rdavydov** [comment]
### `enable_analytics` option in `twitch_minerfile` toggles Analytics needed for the `analytics()` method

Disabling Analytics significantly reduces memory consumption and saves some disk space by not creating and writing `/analytics/*.json`.

Set this option to `True` if you need Analytics. Otherwise set this option to `False` (default value).

See `example.py`. If no such option - defaults to `False`.

Here's the release "for noobs" as usual: https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2/releases/tag/1.3.4

**Comment by rdavydov** [comment]
Everything should work the same as before, you just need to add `enable_analytics=True` option to `twitch_minerfile` if you had Analytics enabled. Tested on localhost - 127.0.0.1 works.

@NoxRare please try this update.

**Comment by NoxRare** [comment]
Confirmed! It works perfectly!

**Pull request closed without merging**
