### PR TITLE
Discord like Telegram Integration

### PR DESCRIPTION
**Pull request by prograstinator**
# Description

Add Telegram like Discord Webhook Notifications

Fixes a part of #320 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)

# How Has This Been Tested?

I created a Webhook, copied the example.py, edited the URL and ran it.

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented on my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation (README.md)
- [X] My changes generate no new warnings
- [X] Any dependent changes have been updated in requirements.txt

### CODE REVIEW

**Comment by Tkd-Alex** [comment]
Wow! Nice! Really appreciate :smiley: 
I'll try asap

**Comment by prograstinator** [comment]
Because I am not an native English speaker I don't know if it is "Discord like Telegram Integration" or "Telegram like Discord Integration".

**Comment by Tkd-Alex** [comment]
> Because I am not an native English speaker I don't know if it is "Discord like Telegram Integration" or "Telegram like Discord Integration".

Don't worry, I'm Italian

**Comment by Tkd-Alex** [comment]
Please follow this guidelines
https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/blob/master/CONTRIBUTING.md#python-styleguide

**Comment by Tkd-Alex** [comment]
uhm 
- Please rename the file `DiscordWebhook.py` to `Discord.py`
- I think the attribute `discord_webhook_api` can be renamed to `webhook_api`
- The followings line probably are duplicated https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/blob/2564cd6da58d2c0b1bc693902652fc1945483dc9/TwitchChannelPointsMiner/logger.py#L140-L148

**Comment by prograstinator** [comment]
Now good? @Tkd-Alex

**Comment by Tkd-Alex** [comment]
:thinking: Why we need this commit? https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/pull/433/commits/cdb5ae0f0c97dd8b9e91e9ddd057ab00513aa179

**Comment by Tkd-Alex** [comment]
> thinking Why we need this commit? [cdb5ae0](https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/commit/cdb5ae0f0c97dd8b9e91e9ddd057ab00513aa179)

Due to the last commit I'm unable to use this branch
```
  File "..../Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/logger.py", line 128, in format
    True if self.settings.telegram.chat_id == 123456789 else False
AttributeError: 'NoneType' object has no attribute 'chat_id'
Call stack:
```

**Comment by prograstinator** [comment]
> thinking Why we need this commit? [cdb5ae0](https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/commit/cdb5ae0f0c97dd8b9e91e9ddd057ab00513aa179)

I wanted to check if the config was changed and not just example.py copied to not send unnecessary requests to discord

**Comment by prograstinator** [comment]
Does is work know? @Tkd-Alex

**Comment by prograstinator** [comment]
Is it good so? @Tkd-Alex

**Pull request merged**
