### PR TITLE
Update streamers's settings run-time

### LINKED ISSUE #62: 'Follow'ing updates
Currently if followers=True then your follows are loaded at start-up only.

A custom (run.py setting) hourly value allowing periodically checking would be helpful.
So you can make changes to followers without restarting the script, if remotely located for example.

### LINKED ISSUE #73: Load streamers while running run.py
Isn't there an alternative way to check in a faster way if a twitch user is online?  If it were implemented it would improve the speed of loading this utility as I for example have 84 people in a row and I usually change the settings quite often.

### PR DESCRIPTION
**Pull request by Tkd-Alex**
- Close #62
- Close #73

Read the appropriate README.md for understand how It's work.
Testers are welcome :partying_face: 

```
15/02/21 12:44:19 - INFO - [__reload_streamers]: 📋  Load 21 streamers from: [STREAMERS]
15/02/21 12:44:19 - INFO - [__reload_streamers]: 📋  Load 54 streamers from: [JSON FILE]
15/02/21 12:44:20 - INFO - [__reload_streamers]: 📋  Load 24 streamers from: [FOLLOWERS]
15/02/21 12:44:20 - INFO - [__reload_streamers]: 🤓  Loading data for new 5 streamers. Please wait...
```
```
15/02/21 12:49:48 - INFO - [__reload_streamers]: 📋  Load 21 streamers from: [STREAMERS]
15/02/21 12:49:48 - INFO - [__reload_streamers]: 📋  Load 53 streamers from: [JSON FILE]
15/02/21 12:49:49 - INFO - [__remove_missing]: 🗑  Remove the streamer: xxxxx. User was unfollowed
15/02/21 12:49:49 - INFO - [__reload_streamers]: 📋  Load 22 streamers from: [FOLLOWERS]
15/02/21 12:49:49 - INFO - [__reload_streamers]: 🤓  Loading data for new 0 streamers. Please wait...
```

### CODE REVIEW

**Comment by kelukelol** [comment]
Could you please sync this with master? I would love to test this out with new updates

**Comment by Tkd-Alex** [comment]
Merge done, but not tested :rofl:

**Comment by kelukelol** [comment]
`13/03/21 15:24:09 - ERROR - TwitchChannelPointsMiner.classes.Twitch - [send_minute_watched_events]: Exception raised in send minute watched
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Twitch-Channel-Points-Miner-v2-json-settings\TwitchChannelPointsMiner\classes\Twitch.py", line 290, in send_minute_watched_events
    streamers[index].settings.watch_streak is True
AttributeError: 'NoneType' object has no attribute 'watch_streak'`
And its repeating itself over and over

**Comment by Tkd-Alex** [comment]
I had this type of errors more weeks ago, I don't remember why. 
 1. Please remove the settings.json file (my bad, I've uploaded in another branch)
 2. Have you tried to add and/or remove streamers at runtime, or It's an error that appear with default settings?

Currently in testing. No issue for me :confused:

**Comment by kelukelol** [comment]
> 1. Please remove the settings.json file (my bad, I've uploaded in another branch)
> 2. Have you tried to add and/or remove streamers at runtime, or It's an error that appear with default settings?
1.  Already did that before starting the script.
2. No, it appears with default settings.
I already hate owning windows instead of Linux tbh :/

**Comment by Tkd-Alex** [comment]
Are you able to share your settings? If you don't want to share publicly reach me privately.

**Comment by kelukelol** [comment]
> Are you able to share your settings? If you don't want to share publicly reach me privately.

Just did it in Telegram.

**Comment by ReddeR1337** [comment]
Any news when it will be in master build ?

**Pull request closed without merging**
