### PR TITLE
Features/improvements to analytics 

### LINKED ISSUE #117: Ideas for features/improvements to analytics
1. A feature to sort streamers by current point totals as well as alphabetical order. Sort by online/offline status as well possibly.

2. A separate graph that includes the points/changes/etc from all tracked streamers in one, showing the sum total of points in all channels that are tracked by the bot. Ability to include/exclude streamers from this graph would be useful too, maybe have checkboxes for all the streamers and a select/deselect all button.

3. Move the list of streamers to the side of the graph, and make it vertical instead of horizontal at the top. Would really help when you have a big list of streamers.

4. Option to only show stats from x date/time without having to zoom in or select the last part of the graph and/or a zoom in option that always zooms in to the last part of the graph instead of in the middle of it.

### PR DESCRIPTION
**Pull request by Tkd-Alex**
# Description

 - [x] A feature to sort streamers by current point totals as well as alphabetical order. ~~Sort by online/offline status as well possibly.~~
 - [ ] ~~A separate graph that includes the points/changes/etc from all tracked streamers in one, showing the sum total of points in all channels that are tracked by the bot. Ability to include/exclude streamers from this graph would be useful too, maybe have checkboxes for all the streamers and a select/deselect all button.~~
 - [x] Move the list of streamers to the side of the graph, and make it vertical instead of horizontal at the top. Would really help when you have a big list of streamers.
 - [x] Option to only show stats from x date/time without having to zoom in or select the last part of the graph and/or a zoom in option that always zooms in to the last part of the graph instead of in the middle of it.

Fixes #117

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (README.md)
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by RakSrinaNa** [comment]
I think it's be nice at some point to reconsider the `Option to only show stats from x date/time without having to zoom in or select the last part of the graph and/or a zoom in option that always zooms in to the last part of the graph instead of in the middle of it.`.

I'd kinda see it another way as a restriction from the server instead, to `only send back the last x days of data to the webpage`.
As it is now I have analytics data that are way too big and makes the whole browser freeze and turn the whole analytics thing unusable (it takes literally 5 mins to load up the graph and then can barely interact with it) (without the annotations it's better but still loading up the graph isn't smooth at all). 

image
(There's about 16k points and 2k events.)

The only way for that would be for me to purge the whole analytics and starts new, but in that case what's the point of the analytics at all?

Maybe this could be seen another way as `Keep last x days of analytics data`. Because also I don't know if it is verry efficient to always read a file quite frequently (at least once every 5mins) with 16k points + 2k events  (and more in the futures) events in it to then save it after adding 1 entry...

Another way maybe, would be to consolidate data at some point. Like `after x days only keep 1 point for each day`, `after x weeks keep 1 point for each week`, ... Like that the whole history could be kept while still making the page usable.

**Comment by Tkd-Alex** [comment]
Agree, already working on it :)

**Comment by Tkd-Alex** [comment]
+ another idea it's to use a database instead of JSON 😂

**Comment by Michael1297** [comment]
small bug: Today's analytics is displayed tomorrow.
<details><summary>today:</summary>


</details><br/>

<details><summary>tomorrow:</summary>


</details><br/>

**Comment by Tkd-Alex** [comment]
@Michael1297 can you test with another browsers? I'm scared about the parsing, the format should be MM.dd

**Comment by Michael1297** [comment]
Also in Microsoft Edge and Mozilla Firefox
Maybe it's because of the time zone

**Comment by Michael1297** [comment]
> Now It's fixed? :)

no

**Comment by Tkd-Alex** [comment]
> > Now It's fixed? :)
> 
> no Now time is displayed correctly but date still requires +1 day

Look at the latest commit :)

**Comment by Michael1297** [comment]
Fixed ✔️😊

**Review by walkxcode — COMMENTED** [review]
Getting error
```
Traceback (most recent call last):
  File "M:\files\Twitch-Channel-Points-Miner-v2\example.py", line 11, in <module>
    twitch_miner = TwitchChannelPointsMiner(
  File "M:\files\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\TwitchChannelPointsMiner.py", line 114, in __init__
    current_version, github_version = check_versions()
  File "M:\files\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\utils.py", line 181, in check_versions
    github_version = init2dict(r.text)["version"]
KeyError: 'version'
```

**Comment by snwfdhmp** [comment]
Hey, why did you strikethrough this ? I'm very much interested by this feature.

>  A separate graph that includes the points/changes/etc from all tracked streamers in one, showing the sum total of points in all channels that are tracked by the bot. Ability to include/exclude streamers from this graph would be useful too, maybe have checkboxes for all the streamers and a select/deselect all button.

**Comment by walkxcode** [comment]
> > Getting error
> > ```
> > Traceback (most recent call last):
> >   File "M:\files\Twitch-Channel-Points-Miner-v2\example.py", line 11, in <module>
> >     twitch_miner = TwitchChannelPointsMiner(
> >   File "M:\files\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\TwitchChannelPointsMiner.py", line 114, in __init__
> >     current_version, github_version = check_versions()
> >   File "M:\files\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\utils.py", line 181, in check_versions
> >     github_version = init2dict(r.text)["version"]
> > KeyError: 'version'
> > ```
> 
> Synced with master-branch, please test now :)

Works now! Although on Docker getting the error
```
Traceback (most recent call last):
  File "/usr/src/app/run.py", line 5, in <module>
    from TwitchChannelPointsMiner import TwitchChannelPointsMiner
  File "/usr/src/app/TwitchChannelPointsMiner/__init__.py", line 3, in <module>
    from .TwitchChannelPointsMiner import TwitchChannelPointsMiner
  File "/usr/src/app/TwitchChannelPointsMiner/TwitchChannelPointsMiner.py", line 14, in <module>
    from TwitchChannelPointsMiner.classes.AnalyticsServer import AnalyticsServer
  File "/usr/src/app/TwitchChannelPointsMiner/classes/AnalyticsServer.py", line 8, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
```

**Comment by walkxcode** [comment]
I've fixed all errors, the graph seems to have a small bug where it goes down every time before going up again 
image

**Comment by Tkd-Alex** [comment]
> Hey, why did you strikethrough this ? I'm very much interested by this feature.
> 
> > A separate graph that includes the points/changes/etc from all tracked streamers in one, showing the sum total of points in all channels that are tracked by the bot. Ability to include/exclude streamers from this graph would be useful too, maybe have checkboxes for all the streamers and a select/deselect all button.

It's not an easy task to implement :roll_eyes:

**Comment by snwfdhmp** [comment]
I just managed to compute the sum :  

image

I made it by generating a `+total.json` in `/analytics/<username>` . I used JavaScript as I'm much more familiar with JavaScript and not so much with Python.

Should I share my script here ? Can you port it to python ? It's a pretty simple script.

I think it can be run every hour without much performance issue, see the result of the `time` command below :

```
real    0m0.698s
user    0m0.015s
sys     0m0.047s
``` 

(running on a AMD Ryzen 7 5800X 8 Core 3.80GHz)

**Comment by Tkd-Alex** [comment]
I think I'll do the merge of this PR asap.
It was created a long time ago and seems to be stable.

About the merge points/sum feature, we can open another PR in the future and maybe add other analytics stats https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/issues/423#issuecomment-1054501336

**Comment by nstwf-pro** [comment]
Hi
Now i got an error while executing script. Start testing today. 
Thanks

```
Traceback (most recent call last):
  File "run.py", line 7, in <module>
    from TwitchChannelPointsMiner.classes.Chat import ChatPresence
ImportError: cannot import name 'ChatPresence' from 'TwitchChannelPointsMiner.classes.Chat' (/home/default/twitch-miner/TwitchChannelPointsMiner/classes/Chat.py)
```

**Comment by Tkd-Alex** [comment]
Ops, probably it's not sync the master branch

**Comment by ColinShark** [comment]
Loving these changes, the UI is way smoother with the 1-week default view. Noticed some "breaking" changes, as the old `join_chat: bool` became `chat: ChatPresence`. This should probably be pointed out in update notes/changelogs, or wherever appropriate.

Specifically this line is obsolete: https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/blob/improvements-analytics/README.md?plain=1#L491

**Comment by snwfdhmp** [comment]
@Tkd-Alex I created a gist : https://gist.github.com/snwfdhmp/20d46a0eb5a3518679d96a0816585d40

> > I just managed to compute the sum :
> > image
> > I made it by generating a `+total.json` in `/analytics/<username>` . I used JavaScript as I'm much more familiar with JavaScript and not so much with Python.
> > Should I share my script here ? Can you port it to python ? It's a pretty simple script.
> > I think it can be run every hour without much performance issue, see the result of the `time` command below :
> > ```
> > real    0m0.698s
> > user    0m0.015s
> > sys     0m0.047s
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Running on a AMD Ryzen 7 5800X 8 Core 3.80GHz, following around 190 streamers for about 3 months.
> 
> Nice work! Yes ofc, please share here :)

@Tkd-Alex I created a gist : https://gist.github.com/snwfdhmp/20d46a0eb5a3518679d96a0816585d40

**Pull request merged**
