### PR TITLE
Use GraphQL instead of Helix API

### LINKED ISSUE #281: "X streamer does not exist" - Happens when launching run.py
When I started my point miner today, this issue appeared. I'm not sure what caused the issue because all of my settings are the same and I haven't changed a single thing.

I have attached a screenshot of the issue and a pastebin (without personal info ofc) of my run.py.

OS: Windows 11 (Beta Channel)

Python 3.9

RUN.PY PASTEBIN: https://pastebin.com/raw/vh0g6Fcd

SCREENSHOT OF ERROR: https://i.imgur.com/f7Hzn9E.png 

EDIT: Before posting this, I reinstalled the miner, didn't work.

--------------------------------------------------------------------------------

EDIT 2:

There has been a [little fix](https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/pull/288) that works perfectly for now!

[Use This](https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/tree/wout-helix-api)

### PR DESCRIPTION
**Pull request by Tkd-Alex**
# Description

The current Client-ID seems to don't work any more for the Helix API request.
Current workaround It's to use the GraphQL request to get streamer_id and followers list.

Fixes #281 #284 #292 #293

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (README.md)
- [x] My changes generate no new warnings
- [x] Any dependent changes have been updated in requirements.txt

### CODE REVIEW

**Comment by borzaka** [comment]
It's working for me, thank you!

image

**Review by RakSrinaNa — APPROVED** [review]

**Comment by Equ1no0x** [comment]
Confirmed working for me as well. Win10 Pro 21H1 19043.1110
Only swapped the 3 files with new changes.
Thank you!
image

**Comment by Coldblackice** [comment]
Working for me, too, thanks. You're doing the lord's work 🙏

**Comment by sad1k** [comment]
thanks for quick answer it work!

**Comment by VitaliShilov** [comment]
do not work, just closed after few minutes

**Comment by Tkd-Alex** [comment]
> do not work, just closed after few minutes

Can you say more about that?

**Comment by DarkVypr** [comment]
Worked perfectly! Just copied cookies over and no issues. Thanks!

(I would also suggest everyone to do this for emoji support)

https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/issues/259

**Comment by VitaliShilov** [comment]
> > do not work, just closed after few minutes
> 
> Can you say more about that?
[20210929-223426.log](https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/files/7254611/20210929-223426.log)

**Comment by ExtremSnek** [comment]
I can't find the latest version of the twitch miner, idk how to import it.

**Comment by Nakustix** [comment]
After a few mins i get this:

30/09 04:38:32 - Exception raised for topic: community-points-user-v1 and message: {'type': 'points-earned', 'data': {'timestamp': '2021-09-30T02:38:30.561978337Z', 'channel_id': '254735295', 'point_gain': {'user_id': 'xxxxxxxxxx', 'channel_id': 'xxxxxxxxx', 'total_points': 10, 'baseline_points': 10, 'reason_code': 'WATCH', 'multipliers': []}, 'balance': {'user_id': 'xxxxxxxxx', 'channel_id': 'xxxxxxxxx', 'balance': 570}}}
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/classes/WebSocketsPool.py", line 182, in on_message
    ws.streamers[streamer_index].persistent_series(
  File "/data/data/com.termux/files/home/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/classes/entities/Streamer.py", line 219, in persistent_series
    self.__save_json("series", event_type=event_type)
  File "/data/data/com.termux/files/home/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/classes/entities/Streamer.py", line 234, in __save_json
    json_data = json.load(open(fname, "r")) if os.path.isfile(fname) else {}
  File "/data/data/com.termux/files/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/data/data/com.termux/files/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/data/data/com.termux/files/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/data/com.termux/files/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

No idea how python works. Kinda need help fixing

**Comment by RakSrinaNa** [comment]
This has probably nothing to do with this pr and has been answered several times in other issues. You seem to have corrupted analytics files.

**Comment by loki181920** [comment]
Hi. Can u explain the steps to fiz this issue? TKS

**Comment by RakSrinaNa** [comment]
There's a search features in the issues for a reason.
#266 among others

**Comment by loki181920** [comment]
> There's a search features in the issues for a reason. #266 among others

sry but i dont understand anything about this XD
thats why i asked

**Comment by vykend** [comment]
Works fine on Ubuntu 20.04 LTS, I've kept old cookies and `run.py` (just `git checkout` to other branch and everything is working it seems).

**Comment by Rafa-Alex** [comment]
is already working without any problem

**Comment by RakSrinaNa** [comment]
> > 
> 
> > 
> 
> > > There's a search features in the issues for a reason. #266 among others
> 
> > 
> 
> > sry but i dont understand anything about this XD thats why i asked
> 
> 
> 
> You need to use this one: https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/tree/wout-helix-api 
> 
> 
> 
> @loki181920
> 
> 

Not really. The issue he mentions (analytics Json issue) has nothing to do with this PR and is related to another issue than has been answered several times, hence the 266 I linked.

**Comment by loki181920** [comment]
Tks um going to try

**Comment by EEEmill** [comment]
I have "re-installed" and got this now.

`30/09/21 17:43:31 - INFO - [run]: 😢  Streamer --- does not exist
30/09/21 17:43:31 - INFO - [run]: 😢  Streamer --- does not exist
Traceback (most recent call last):
  File "C:\Users\-\Desktop\Twitch-Channel-Points-Miner-v2-master\run2.py", line 65, in <module>
    twitch_miner.mine(
  File "C:\Users\-\Desktop\Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\TwitchChannelPointsMiner.py", line 122, in mine
    self.run(streamers=streamers, blacklist=blacklist, followers=followers)
  File "C:\Users\-\Desktop\Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\TwitchChannelPointsMiner.py", line 246, in run
    user_id=self.twitch.twitch_login.get_user_id(),
  File "C:\Users\-\Desktop\Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\classes\TwitchLogin.py", line 214, in get_user_id
    return int(self.get_cookie_value("persistent").split("%")[0])
AttributeError: 'NoneType' object has no attribute 'split'`

**Comment by RakSrinaNa** [comment]
> I have "re-installed" and got this now.
> 
> `30/09/21 17:43:31 - INFO - [run]: 😢 Streamer --- does not exist 30/09/21 17:43:31 - INFO - [run]: 😢 Streamer --- does not exist Traceback (most recent call last): File "C:\Users\-\Desktop\Twitch-Channel-Points-Miner-v2-master\run2.py", line 65, in <module> twitch_miner.mine( File "C:\Users\-\Desktop\Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\TwitchChannelPointsMiner.py", line 122, in mine self.run(streamers=streamers, blacklist=blacklist, followers=followers) File "C:\Users\-\Desktop\Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\TwitchChannelPointsMiner.py", line 246, in run user_id=self.twitch.twitch_login.get_user_id(), File "C:\Users\-\Desktop\Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\classes\TwitchLogin.py", line 214, in get_user_id return int(self.get_cookie_value("persistent").split("%")[0]) AttributeError: 'NoneType' object has no attribute 'split'`

You're still using the master branch and not wout-helix-api.

**Comment by EEEmill** [comment]
> 
> 
> > I have "re-installed" and got this now.
> > `30/09/21 17:43:31 - INFO - [run]: 😢 Streamer --- does not exist 30/09/21 17:43:31 - INFO - [run]: 😢 Streamer --- does not exist Traceback (most recent call last): File "C:\Users\-\Desktop\Twitch-Channel-Points-Miner-v2-master\run2.py", line 65, in <module> twitch_miner.mine( File "C:\Users\-\Desktop\Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\TwitchChannelPointsMiner.py", line 122, in mine self.run(streamers=streamers, blacklist=blacklist, followers=followers) File "C:\Users\-\Desktop\Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\TwitchChannelPointsMiner.py", line 246, in run user_id=self.twitch.twitch_login.get_user_id(), File "C:\Users\-\Desktop\Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\classes\TwitchLogin.py", line 214, in get_user_id return int(self.get_cookie_value("persistent").split("%")[0]) AttributeError: 'NoneType' object has no attribute 'split'`
> 
> You're still using the master branch and not wout-helix-api.

Ok, I have read something about it. Can you explain more what I should do with it? Just "install" it?
https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/tree/wout-helix-api

**Comment by RakSrinaNa** [comment]
> > > I have "re-installed" and got this now.
> > > `30/09/21 17:43:31 - INFO - [run]: 😢 Streamer --- does not exist 30/09/21 17:43:31 - INFO - [run]: 😢 Streamer --- does not exist Traceback (most recent call last): File "C:\Users\-\Desktop\Twitch-Channel-Points-Miner-v2-master\run2.py", line 65, in <module> twitch_miner.mine( File "C:\Users\-\Desktop\Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\TwitchChannelPointsMiner.py", line 122, in mine self.run(streamers=streamers, blacklist=blacklist, followers=followers) File "C:\Users\-\Desktop\Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\TwitchChannelPointsMiner.py", line 246, in run user_id=self.twitch.twitch_login.get_user_id(), File "C:\Users\-\Desktop\Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\classes\TwitchLogin.py", line 214, in get_user_id return int(self.get_cookie_value("persistent").split("%")[0]) AttributeError: 'NoneType' object has no attribute 'split'`
> > 
> > 
> > You're still using the master branch and not wout-helix-api.
> 
> Ok, I have read something about it. Can you explain more what I should do with it? Just "install" it? https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/tree/wout-helix-api

```
git clone https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2
cd Twitch-Channel-Points-Miner-v2
git checkout wout-helix-api
```

if the concept of branches isn't so familiar maybe it's better staying on master and wait that this is merged and just do a `git pull` then.

**Comment by borzaka** [comment]
With currently the latest `wout-helix-api` feature branch changes: `Updating 5f6c755..3c31015`
```
$ python run.py 
30/09 23:08:21 - 🌐  Analytics running on http://0.0.0.0:5000/
30/09 23:08:21 - 💣  Start session: 'xxx'
30/09 23:08:21 - 🤓  Loading data for 4 streamers. Please wait...
30/09 23:08:27 - 😴  xxx (49.21k points) is Offline!
30/09 23:08:28 - 😴  yyy (27.52k points) is Offline!
30/09 23:08:30 - 😴  zzz (11.38k points) is Offline!
30/09 23:08:31 - 😴  www (18.99k points) is Offline!
^C30/09 23:08:36 - CTRL+C Detected! Please wait just a moment!
Traceback (most recent call last):
  File "run.py", line 75, in <module>
    twitch_miner.mine(
  File "/home/xxx/Downloads/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/TwitchChannelPointsMiner.py", line 122, in mine
    self.run(streamers=streamers, blacklist=blacklist, followers=followers)
  File "/home/xxx/Downloads/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/TwitchChannelPointsMiner.py", line 227, in run
    time.sleep(30)
  File "/home/xxx/Downloads/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/TwitchChannelPointsMiner.py", line 307, in end
    self.ws_pool.end()
AttributeError: 'NoneType' object has no attribute 'end'
```

**Comment by SnugglyFruit** [comment]
> > > > I have "re-installed" and got this now.
> > > > `30/09/21 17:43:31 - INFO - [run]: 😢 Streamer --- does not exist 30/09/21 17:43:31 - INFO - [run]: 😢 Streamer --- does not exist Traceback (most recent call last): File "C:\Users\-\Desktop\Twitch-Channel-Points-Miner-v2-master\run2.py", line 65, in <module> twitch_miner.mine( File "C:\Users\-\Desktop\Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\TwitchChannelPointsMiner.py", line 122, in mine self.run(streamers=streamers, blacklist=blacklist, followers=followers) File "C:\Users\-\Desktop\Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\TwitchChannelPointsMiner.py", line 246, in run user_id=self.twitch.twitch_login.get_user_id(), File "C:\Users\-\Desktop\Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\classes\TwitchLogin.py", line 214, in get_user_id return int(self.get_cookie_value("persistent").split("%")[0]) AttributeError: 'NoneType' object has no attribute 'split'`
> > > 
> > > 
> > > You're still using the master branch and not wout-helix-api.
> > 
> > 
> > Ok, I have read something about it. Can you explain more what I should do with it? Just "install" it? https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/tree/wout-helix-api
> 
> ```
> git clone https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2
> cd Twitch-Channel-Points-Miner-v2
> git checkout wout-helix-api
> ```
> 
> if the concept of branches isn't so familiar maybe it's better staying on master and wait that this is merged and just do a `git pull` then.

I know nothing about any of this but I figured out the instructions you've written and now it works perfectly! it took me few minutes to realize that I needed to link the directory after the cd. I spent too much time copy-pasting and double-checking everything but I remembered the cd step during installation...... eventually... Anywho, thank you!

**Comment by RakSrinaNa** [comment]
> With currently the latest `wout-helix-api` feature branch changes: `Updating 5f6c755..3c31015`
> 
> ```
> 
> $ python run.py 
> 
> 30/09 23:08:21 - 🌐  Analytics running on http://0.0.0.0:5000/
> 
> 30/09 23:08:21 - 💣  Start session: 'xxx'
> 
> 30/09 23:08:21 - 🤓  Loading data for 4 streamers. Please wait...
> 
> 30/09 23:08:27 - 😴  xxx (49.21k points) is Offline!
> 
> 30/09 23:08:28 - 😴  yyy (27.52k points) is Offline!
> 
> 30/09 23:08:30 - 😴  zzz (11.38k points) is Offline!
> 
> 30/09 23:08:31 - 😴  www (18.99k points) is Offline!
> 
> ^C30/09 23:08:36 - CTRL+C Detected! Please wait just a moment!
> 
> Traceback (most recent call last):
> 
>   File "run.py", line 75, in <module>
> 
>     twitch_miner.mine(
> 
>   File "/home/xxx/Downloads/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/TwitchChannelPointsMiner.py", line 122, in mine
> 
>     self.run(streamers=streamers, blacklist=blacklist, followers=followers)
> 
>   File "/home/xxx/Downloads/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/TwitchChannelPointsMiner.py", line 227, in run
> 
>     time.sleep(30)
> 
>   File "/home/xxx/Downloads/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/TwitchChannelPointsMiner.py", line 307, in end
> 
>     self.ws_pool.end()
> 
> AttributeError: 'NoneType' object has no attribute 'end'
> 
> ```

This isn't linked to this PR.
#293

**Comment by RakSrinaNa** [comment]
@Tkd-Alex i think this would be great merging this somewhat soon. This seem stable enough and is a blocking issue that brings a lot of confusion in the issues recently.

**Pull request merged**
