### PR TITLE
Use requests.Session() in Twitch class

### PR DESCRIPTION
**Pull request by njallam**
# Description

All requests made in `Twitch.py` now use the same `requests.Session()`.  `gql.twitch.tv` requests in particular are extremely frequent, and this change avoids the need for a DNS request + a new HTTP connection for each one (keep-alive allows requests to reuse an existing connection).

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Miner initialises and runs as normal.  DNS requests are significantly less frequent.

The "Top Permitted Domains" table shows the most popular domain names for my home network.  The query log (below) shows requests for `gql.twitch.tv` from the machine that runs Twitch-Channel-Points-Miner.

| Before | After |
| --- | --- |
| Top domains 2021-03-03 | Top domains 2021-03-04 |
| Pi-hole query log before | Pi-hole query log after |

DNS requests for `gql.twitch.tv` drop from ~38585 per day (consistently this high every day) down to ~197 per day following this change.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (README.md)
- [x] My changes generate no new warnings
- [x] Any dependent changes have been updated in requirements.txt

### CODE REVIEW

**Comment by Tkd-Alex** [comment]
Awesome! :partying_face:

**Comment by Tkd-Alex** [comment]
It is normal? @njallam 
image

**Comment by Tkd-Alex** [comment]
Maybe we should use an array of Session? One for each Streamer?

**Comment by RakSrinaNa** [comment]
Also to avoid more problems of scaling, could set `pool_block=False`. This will block the connection until a slot is available instead of dropping it. You'll need to set `pool_maxsize=xxx` too.
 
> :param block:         If set to True, no more than **maxsize** connections will be used at a time. When no free connections are available, the call will block until a connection has been released.

**Comment by PureFallen** [comment]
Another side effect of the commit @bbcaec1 seems to be, that the existing connection (instead of making new ones each time) might be closed on Twitch´s End when the last respond was more than X seconds ago (Timeout). This get's problematic, as the delay between each "send_minute_watched_event" is 60 seconds of waittime + the delay that comes from the script execution and request itself.

This seems to happen when Channelpoints are collected for one Streamer only (others are offline) or theoretically, when the Channelpoints of two Streamer are collected at the same time. Awarded Channelpoints are reduced by 50%+ that way.

Quick and Dirty Fix is for now up fill up the Streamer List with 24/7 Streams at lowest priority as some kind of "Fallback" hoping that always atleast two Streams are active, including the ones with higher priority someone is actually going for.
But we probably will have to look into a way of "keeping the connection alive" when the next request is expected to come more than 60 seconds later.

send_minute_watch_events for 2 Streamer with 30s delay inbetween:
j9liJK6

Collecting Channelpoints for 1 Streamer:
izv3jAE

(Nothing useful on DEBUG Log other than the error that already made it into the INFO log.)

**Comment by Tkd-Alex** [comment]
This pull request create some little errors and other problems. I've reverted the master branch and delete the commit on this PR.
My bad I've merged the PR before doing aggressive test on it, my apology. :crying_cat_face: 

@njallam 
Please If you have free time find a way to fix and the others issues reported here and create a new PR.
Or if someone else wants to work on it. For the next week I'm very busy.

**Pull request merged**
